version: "3.0"

services:
    # Node Service:
    chat_app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: benzo203/chat_app_nodejs-chat_app:latest
        tty: true
        restart: unless-stopped
        networks:
            - chat_app_network
        depends_on:
            - chat_app_redis

    # Nginx Service:
    chat_app_nginx:
        image: nginx:1.25.4
        container_name: chat_app_nginx
        tty: true
        restart: unless-stopped 
        networks:
            - chat_app_network
        depends_on:
            - chat_app

    # Redis Service
    chat_app_redis:
        image: redis:7.2.4
        container_name: chat_app_redis
        restart: unless-stopped
        tty: true
        ports:
            - "6379:6379"
        networks:
            - chat_app_network
# Network
networks:
    chat_app_network:
        driver: bridge

