version: "3.0"

services:
  # Node Service:
  chat_app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    env_file:
      - .env.production

    command: npm start

  # Nginx Service:
  chat_app_nginx:
    ports:
      - "80:80"
