name: Docker Image CI

on:
  push:
    branches: [ "tuananh_test" ]
  pull_request:
    branches: [ "tuananh_test" ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v4
    - 
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - 
      name: Build New Image
      uses: docker-compose -f docker-compose.yml -f docker-compose.production.yml build chat_app
    - 
      name: Push Image to DockerHub
      uses: docker compose -f docker-compose.yml -f docker-compose.production.yml push chat_app
     
        
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH to EC2 and execute command
      uses: appleboy/ssh-action@v0.2.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.EC2_PORT }}

    - name: Move to folder project
      run: |
        cd ~
        cd project/chat_app_nodejs
    
    - name: Pull code
      run: git pull origin tuananh_test
    - name: Login before pull
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Pull Docker Registry
      run: docker compose -f docker-compose.yml -f docker-compose.docker-compose.production.yml pull
    - name: Run docker container
      run: docker compose -f docker-compose.yml -f docker-compose.docker-compose.production.yml up -d --no-deps chat_app
  
