name: Docker Image CI

on:
  push:
    branches: [ "tuananh_test" ]
  pull_request:
    branches: [ "tuananh_test" ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      run: |
        docker-compose -f docker-compose.yml build
        docker-compose -f docker-compose.yml push
        
  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
    - name: Pull compose from docker hub
      run: docker-compose pull
    - name: Delete old container
      run: docker-compose down
    - name: Run docker container
      run: docker-compose up -d
  
